Added pgadmin
MrFox131/fefu_backend_2_3 pull request #1
Opened 2021-09-23 10:45 UTC by MrFox131

2021-09-28 15:32 UTC, chrn-feip requested changes
Приведите, пожалуйста, сообщения коммита тут и в основной ветке к формату, описанному в материалах курса.

2021-09-28 15:32 UTC, chrn-feip commented on docker-compose.yml
> +        links:
Зачем это понадобилось?

2021-09-28 15:32 UTC, chrn-feip commented on docker-compose.yml
> +            PGADMIN_DEFAULT_EMAIL: enginer385@gmail.com
Не надо хардкодить значения настроек и тем более не надо коммитить в репозиторий приватные данные. Правильно это будет вынести в .env (и .env.example с пустыми значениями, например, который попадёт в коммит). Касается секций environment и ports.
Так гибче управлять конфигурацией и в случае чего понадобится только поменять .env (который не лежит в репозитории) вместо изменения docker-compose.yml (который под контролем версий) и деплоя изменений на сервер/коммит в репозиторий. А приватные данные в коде - это большая дыра в безопасности.

2021-09-28 15:32 UTC, chrn-feip commented on docker-compose.yml
> +            PGADMIN_LISTEN_PORT: 2777
Зачем понадобилось переопределить порт?

2021-09-29 07:51 UTC, MrFox131 commented on docker-compose.yml
> +        links:
network? Чтобы pgadmin имел доступ к pgsql по имени этого контейнера внутри созданной докером сети.

2021-09-29 07:53 UTC, MrFox131 commented on docker-compose.yml
> +            PGADMIN_DEFAULT_EMAIL: enginer385@gmail.com
Все приватные данные, которые лежат тут итак в открытом доступе. И даже вроде доступны у меня на странице в github. Уберу.

2021-09-29 07:59 UTC, closed without merging