Lesson 6: Validate and sanitize appeal form input
MrFox131/fefu_backend_2_3 pull request #10
Opened 2021-11-05 11:02 UTC by MrFox131

2021-11-09 13:51 UTC, chrn-feip requested changes

2021-11-09 13:51 UTC, chrn-feip commented on app/Http/Controllers/AppealController.php
> +            $validated = $request->validate([
Правила валидации не тут должны быть. Читайте ДЗ внимательнее.

2021-11-09 13:51 UTC, chrn-feip commented on database/migrations/2021_10_31_075413_create_appeals_table.php
> +            $table->string('surname', 40);
Запрещено модифицировать файлы старых миграций. Они уже применены и повторно в штатном режиме не будут вызваны. Почитайте про назначение миграций и напишите новую.

2021-11-09 13:51 UTC, chrn-feip commented on resources/views/appeal.blade.php
>              <input name="name" class="form-control" required value="{{old('name')}}"/>
Уберите все requeired и прочие атрибуты (type, не равный text), которые задают какую-либо валидацию на фронте.

2021-11-09 13:51 UTC, chrn-feip commented on resources/views/appeal.blade.php
> +        var select = document.getElementById('gender_selecter').children[{{old('gender')}}].selected=true;
Почему не php-кодом? Во-первых, мы пишем бэкенд. Во-вторых, не нужно делать скриптом делать то, что можно не делать. Скрипт всегда отрабатывает после того, как html с сервера загрузился, при условии, что js не выключен в браузере юзера. Мы можем прислать с сервера сразу корректный html.

2021-11-09 13:51 UTC, chrn-feip commented on app/Sanitizers/DigitOnlySanitizer.php
> +class DigitOnlySanitizer
Это уже не просто  DigitOnly, тут уже есть специфика по форматированию номера телефона. Назовите иначе.

2021-11-09 13:51 UTC, chrn-feip commented on app/Sanitizers/DigitOnlySanitizer.php
> +        if ($value[0] == '8') {
Это можно сделать проще. Просто через замену первого символа, независимо от его значения.

2021-11-09 13:51 UTC, chrn-feip commented on app/Http/Controllers/AppealController.php
> +                'age' =>[ 'required','integer','max:125','min:14'],
А есть ещё правило between

2021-11-09 13:51 UTC, chrn-feip commented on app/Http/Controllers/AppealController.php
> +                'phone' => ['nullable', 'string','regex:/^(\+7|8|7)[0-9]{10}$/i'],
Не просто nullable. В ДЗ 5 было требование о том, что телефон или почта должны быть заполнены. Эта проверка тут всё ещё актуальна.

2021-11-09 13:51 UTC, chrn-feip commented on app/Http/Controllers/AppealController.php
> +                'gender' => ['required','integer','in:0,1']
Не пишите 0,1. У вас же есть константы в Gender. Их значения могут измениться, а тут хардкод.

2021-11-11 16:49 UTC, MrFox131 commented on app/Http/Controllers/AppealController.php
> +            $validated = $request->validate([
В лекции я другого метода не нашёл. По крайней мере в качестве примера показывался тот, что применен у меня. А в ходе теор метаериала я хоть и слышал об ином варианте расположеня, но увы, не увидел его в документации например

2021-11-11 16:50 UTC, MrFox131 commented on app/Http/Controllers/AppealController.php
> +                'phone' => ['nullable', 'string','regex:/^(\+7|8|7)[0-9]{10}$/i'],
Не смог найти правило, которое производит бы проверку заполненности одного из двух полей

2021-11-11 16:51 UTC, MrFox131 commented on database/migrations/2021_10_31_075413_create_appeals_table.php
> +            $table->string('surname', 40);
Назначение миграции мне ясно. Когда в прошлый раз я писал миграцию - с этим были проблемы. Все сломалось и отказывалось мигрировать, простт потеряло файлы. Исправлю. Но на лекции такого не помню тоже

2021-11-11 16:53 UTC, MrFox131 commented on resources/views/appeal.blade.php
> +        var select = document.getElementById('gender_selecter').children[{{old('gender')}}].selected=true;
Как это сделать чистым php я знаю. Вы говорили на паре, что возможно есть более органичные методы для решения этой задачи, это мой метод. Исправлю безусловно, но это не от незнания. Простт удобнее и понятнее

2021-11-12 01:12 UTC, chrn-feip commented on app/Http/Controllers/AppealController.php
> +            $validated = $request->validate([
В лекции вам рассказывалось про запрос формы и в примере показывалась такая валидация и оговаривалось, что по ДЗ (там это и написано) нужен запрос формы. Плохо искали: https://laravel.com/docs/8.x/validation#form-request-validation

2021-11-12 01:24 UTC, chrn-feip commented on database/migrations/2021_10_31_075413_create_appeals_table.php
> +            $table->string('surname', 40);
Проговаривала на одной из лекций, когда увидела такие массовые порчи существующих миграций, что так делать нельзя.
Перечитайте 
https://docs.google.com/presentation/d/11a3bivkk2LZSnvs8tRN77q8MuLFuLOqX-5w5Q7qCXJI/edit#slide=id.gf56e809c1d_1_40
https://laravel.com/docs/8.x/migrations#running-migrations

Мне важно знать, очевиден ли алгоритм работы с миграциями из того, что написано в доках и в лекции и было также сказано: миграции предназначены для контроля версий БД, они применяются и могут быть откачены, у вас в БД есть таблица migrations, которая является реестром применённых миграций, по ней команды работы с миграциями понимают текущую версию БД. Если я не ошибаюсь, это ВСЁ было проговорено на лекции.

2021-11-12 01:25 UTC, chrn-feip commented on app/Http/Controllers/AppealController.php
> +                'phone' => ['nullable', 'string','regex:/^(\+7|8|7)[0-9]{10}$/i'],
Плохо искали, поищите ещё: https://laravel.com/docs/8.x/validation#available-validation-rules

2021-11-26 14:26 UTC, chrn-feip commented
Вы живы?

2021-11-29 03:40 UTC, MrFox131 commented
> Вы живы?

У меня были соревнования CTF(в которых мы заняли к слову 3 место и прошли в финал), 2 коммерческих проекта и хакатон. Не было абсолюнто времени. Сейчас сажусь писать

2021-11-29 04:37 UTC, MrFox131 commented on app/Http/Controllers/AppealController.php
> +            $validated = $request->validate([
Ради этого invoke пришлось разделить на два запроса. Потому что если делать typehint с соответствующим form request'ом он валидируется сразу. Незаваисом от типа запроса. Как исправить не нашел. Сделал отдельно post и get

2021-12-07 10:06 UTC, MrFox131 commented
А можно проверить? Уже прошло 8 дней. Я не халявил, у меня, к счастью, помимо мало чего приносите учёбы есть проекты, в том числе коммерческие. И долги как-то закрыть не получится в таком темпе

2021-12-07 12:12 UTC, kivaloff commented on app/Http/Requests/AppealPostRequest.php
> +            'email' => ['nullable','string','max:100','regex:/^[a-z0-9_]+@[a-z0-9]+\.[a-z0-9]{2,6}$/i', 'required_without:phone'],
email должен поддерживать кириллицу

2021-12-08 05:23 UTC, merged