Lesson 5: Add appeal form
MrFox131/fefu_backend_2_3 pull request #9
Opened 2021-11-02 11:27 UTC by MrFox131

2021-11-02 13:42 UTC, chrn-feip requested changes

2021-11-02 13:42 UTC, chrn-feip commented on app/Http/Controllers/AppealController.php
> +            if ($request->input('_token') != csrf_token()){
Это не нужно делать вручную, т.к. проверкой занимается посредник App\Http\Middleware\VerifyCsrfToken

2021-11-02 13:42 UTC, chrn-feip commented on app/Http/Middleware/VerifyCsrfToken.php
> +        '/appeal'
Ах вот оно что. Допустимо, но "велосипед". ОК, я убедилась по вашему варианту кода, что вы понимаете, что делаете. Верните просто назад тут всё и уберите ручную проверку токена из контроллера.

2021-11-02 13:42 UTC, chrn-feip commented on database/migrations/2021_10_31_075413_create_appeals_table.php
> +            $table->decimal('phone', 11, 0, true)->nullable();
Лучше строкой хранить, а не числом. С decimal могут быть побочные эффекты при выборке и запросах.

2021-11-02 13:42 UTC, chrn-feip commented on resources/views/appeal.blade.php
> +            <input name="name" class="form-control" required value="{{old('name')}}"/>
После успешной отправки формы проверяли, что old в форме не выводится?

2021-11-03 02:20 UTC, MrFox131 commented on app/Http/Middleware/VerifyCsrfToken.php
> +        '/appeal'
я так сделал потому что автоматическая проверка отправляет на страницу ошибки. А вы просили в задании высветить уведомление о том что токен истек. Исправлю

2021-11-03 02:20 UTC, MrFox131 commented on resources/views/appeal.blade.php
> +            <input name="name" class="form-control" required value="{{old('name')}}"/>
Проверил, не выводится

2021-11-04 05:09 UTC, merged